experiment_folders:
- results_ga_tokens
- results_gomea_tokens
- results_random_sampler_tokens
experiment_labels:
- GA
- GOMEA
- Random sampler
experiment_markers:
- o
- s
- ^
constant_experiment_folders: null
constant_labels: null
save_folder: results_runcharts_tokens
clean_output: false
metrics:
- hpsv2_score
best_so_far: true
nfe_xscale: linear
time_limit: 500
label_template: '{algorithm}'
figure_width: 6.0
figure_height: 6.0
font_size: 13
marker_size: 6.0
