# Discrete text encoder token experiments. See README.md for parameter semantics.
runs:
- optimization_method: ga
  results_folder: results_ga_tokens
- optimization_method: gomea
  results_folder: results_gomea_tokens
- optimization_method: random_sampler
  results_folder: results_random_sampler_tokens
