# Define source directories containing the result folders
source_dirs: [
  "results_sepcmaes_pixart/sepcmaes_clip_laionv2_pixart_pixartsigmaxl21024ms_42_a0_b100",
  "results_sepcmaes_pixart/sepcmaes_clip_laionv2_pixart_pixartsigmaxl21024ms_42_a50_b50",
  "results_sepcmaes_pixart/sepcmaes_clip_laionv2_pixart_pixartsigmaxl21024ms_42_a100_b0"
  ]
# Define display names for each of the above methods
method_names: [
  "Initial Embedding", # Baseline, do not change
  #"Adam",
  #"Adam a=1.0, b=0.0",
  #"Adam a=0.5, b=0.5",
  #"Adam a=0.0, b=1.0",
  #"sep-CMA-ES",
  "sep-CMA-ES a=0.0, b=1.0",
  "sep-CMA-ES a=0.5, b=0.5",
  "sep-CMA-ES a=1.0, b=0.0",
]

algorithm_labels: [
    ["baseline", "Flux (no optimization)"],
    #["adam", "Adam"],
    ["sepcmaes", "sep-CMA-ES"],
]

save_folder: "results_processed_pixart"

aesthetic_max: 10.0
clip_max: 0.5